# Main configuration file for mkdocs generation of BIGTREETECH.org website

# Note that the build-translations.sh script expects a certain file
# layout.  See that script and the README file for more details.

# Site and directory configuration
site_name: BIGTREETECH WIKI
repo_url: https://github.com/bigtreetech/docs
repo_name: bigtreetech/docs
edit_uri: blob/master/docs/
use_directory_urls: False
docs_dir: '../'
site_dir: '../../site/'

# Custom markdown dialect settings
markdown_extensions:
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - attr_list
  - mdx_partial_gfm
  - mdx_truly_sane_lists
  - mdx_breakless_lists
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      toc_depth: 6
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
plugins:
  search:
    lang: en
  mkdocs-simple-hooks:
    hooks:
      on_page_markdown: "docs._biqumkdocs.mkdocs_hooks:transform"
  exclude:
    glob: "README.md"

# Website layout configuration (using mkdocs-material theme)
theme:
  name: material
  palette:   
    - scheme: default # 日间模式
      primary: blue grey # 上方的
      accent: blue # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: Switch to dark mode # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: grey 
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: img/BQ-BIQU.svg
  favicon: img/favicon.ico  
  icon:
    repo: fontawesome/brands/github
    alternate: material/web
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  language: en
extra_css:
  - _biqumkdocs/css/extra.css
  - _biqumkdocs/css/zoom.css

# Site usage statistics
extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#site-search-tracking
  generator: false
  analytics:
    provider: google
    property: UA-138371409-1
  # Language Selection
  alternate: 
    - name: English
      link: https://bttwiki.com/en/
      lang: en
    - name: 简体中文
      link: https://bttwiki.com/zh/
      lang: zh

# Navigation hierarchy (this should mimic the layout of Overview.md)
nav:
  - BIGTREETECH:
    - Motherboards:
      - SKR Series:
        - SKR MINI E3.md
        - SKR 3 EZ.md
        - SKR 3.md
        - SKR Pico.md
        - SKR PRO V1.2.md
        - SKR V1.4.md
        - SKRat.md
      - Octopus Series:
        - Octopus.md
        - Octopus Pro.md
        - Octopus MAX EZ.md
      - Manta Series:
        - M4P.md
        - M5P.md
        - M8P.md
      - EBB Series:
        - EBB 36 CAN.md
        - EBB 42 CAN.md
        - EBB 2240 2209 CAN.md
        - EBB 2209 CAN RP2040.md
        - U2C.md
      - MMB Series:
        - MMB CAN V1.0.md
    - IOT:
      - CB1.md
      - CB2.md
      - Pi2.md
      - PI4B.md
      - PAD7.md
      - KNOMI.md
      - KNOMI2.md
      - Panda Touch.md
      - Klipper Touch.md
      - Panda Branch.md
    - Displays:
      - TFT43-DIP.md
      - TFT35 E3.md
      - TFT35.md
      - TFT24.md
      - TFT35 SPI.md
      - HDMI5.md
      - HDMI7 V1.0.md
      - HDMI7 V1.2.md
    - Motor Drives:
      - TMC Series:
        - TMC2130.md
        - TMC5160.md
        - TMC2209.md
        - TMC2208.md
        - TMC2240.md
        - TMC5160TPlus.md
        - Tutorials.md
      - EZ Series:
        - EZ2130.md
        - EZ2208.md
        - EZ2225.md
        - EZ2226.md
        - EZ5160 Pro.md
        - EZDriver Connector.md
        - EZ2209.md
        - EZ31865.md
    - Sensors Modules:
      - ADXL345.md
      - SKSM.md
      - Eddy.md
    - Software Tutorials:
      - Multiple 3D Printers.md
      - Software Configuration.md
      - Software Installation.md
      - EBB Series.md
      - libinput_calibration.md    
  - BIQU:
    - Panda series: 
      - Panda Hotend:
        - Panda Flow/CHT:
          - X1:
            - Panda Flow X1.md
          - P1:
            - Panda Flow P1.md
        - Panda Revo:
          - X1:
            - Panda Revo X1 Hotend.md
          - P1:
            - Panda Revo P1 Hotend.md
      - Panda Claw:
          - Panda A1Mini.md
          - Panda P1 X1.md
      - PandaTouch.md
      - Panda Hub.md
      - Panda Jet.md 
      - Panda Fur.md 
      - Panda Lux.md 
    - Extruders: 
      - Extruders.md 
      - H2 V2S.md 
      - H2 V2S Revo.md 
      - H2 V2S Lite.md 
      - H2 V2S Lite Revo.md 
      - H2 V2X.md 
    - Hotends: 
      - Hotends.md 
    - Sensor modules:
      - Hermit Crab 2 Series.md
    - Printers: 
      - Printers.md 
    - tools:
      - belter.md
    - Cooling solution:
      - Universal Turbo Kit.md 

copyright: <a href="https://beian.miit.gov.cn/" target="_blank">粤ICP备2024178516号</a>

